import type { TariffPlan } from './types';

export const DEFAULT_PLANS: TariffPlan[] = [
  // --- 5G畅享套餐 (个人版 - 无宽带) ---
  { id: '20252062', name: '5G畅享套餐39元', price: 39, data: 40, voice: 500, hasBroadband: false, broadbandSpeed: 0, broadbandBaseSpeed: 0, isFTTR: false, isActive: true, extras: '5G优享服务' },
  { id: '20252063', name: '5G畅享套餐49元', price: 49, data: 60, voice: 700, hasBroadband: false, broadbandSpeed: 0, broadbandBaseSpeed: 0, isFTTR: false, isActive: true, extras: '视频彩铃, 任我选黄金会员' },
  { id: '20252064', name: '5G畅享套餐59元', price: 59, data: 80, voice: 900, hasBroadband: false, broadbandSpeed: 0, broadbandBaseSpeed: 0, isFTTR: false, isActive: true, extras: '视频彩铃, 任我选黄金会员' },

  // --- 融合主推 — 5G全家享（AI爱家版）---
  { id: '20263028', name: '71元5G全家享（AI爱家版）', price: 59, data: 80, voice: 900,
    hasBroadband: true, broadbandSpeed: 1000, broadbandBaseSpeed: 500, isFTTR: false, isActive: true,
    extras: 'WIFI6路由器', monthlyTotal: 71,
    targetCarrier: 'all', planCategory: 'broadband' },
  { id: '20263029', name: '81元5G全家享（AI爱家版）', price: 69, data: 90, voice: 1000,
    hasBroadband: true, broadbandSpeed: 1000, broadbandBaseSpeed: 500, isFTTR: false, isActive: true,
    extras: 'WIFI6路由器', monthlyTotal: 81,
    targetCarrier: 'all', planCategory: 'broadband' },
  { id: '20263030', name: '90元5G全家享（AI爱家版）', price: 79, data: 100, voice: 1100,
    hasBroadband: true, broadbandSpeed: 1000, broadbandBaseSpeed: 0, isFTTR: false, isActive: true,
    extras: 'WIFI6路由器', monthlyTotal: 90,
    targetCarrier: 'all', planCategory: 'broadband' },
  { id: '20263031', name: '110元5G全家享（AI爱家版）', price: 99, data: 120, voice: 1300,
    hasBroadband: true, broadbandSpeed: 1000, broadbandBaseSpeed: 0, isFTTR: false, isActive: true,
    extras: 'WIFI6路由器', monthlyTotal: 110,
    targetCarrier: 'all', planCategory: 'broadband' },

  // --- 全光版（FTTR）---
  { id: '20253101', name: '99元5GA全家享(全光版)', price: 99, data: 120, voice: 1300,
    hasBroadband: true, broadbandSpeed: 1000, broadbandBaseSpeed: 0, isFTTR: true, isActive: true,
    extras: 'FTTR1+1, 语音遥控器', monthlyTotal: 99,
    targetCarrier: 'all', planCategory: 'fttr' },
  { id: '20253102', name: '109元5GA全家享(全光版)', price: 109, data: 140, voice: 1400,
    hasBroadband: true, broadbandSpeed: 1000, broadbandBaseSpeed: 0, isFTTR: true, isActive: true,
    extras: 'FTTR1+1, 语音遥控器', monthlyTotal: 109,
    targetCarrier: 'all', planCategory: 'fttr' },
  { id: '20253103', name: '129元5GA全家享(全光版)', price: 129, data: 160, voice: 1500,
    hasBroadband: true, broadbandSpeed: 1000, broadbandBaseSpeed: 0, isFTTR: true, isActive: true,
    extras: 'FTTR1+1, 权益超市铂金', monthlyTotal: 129,
    targetCarrier: 'all', planCategory: 'fttr' },
  { id: '20253104', name: '149元5GA全家享(全光版)', price: 149, data: 180, voice: 1800,
    hasBroadband: true, broadbandSpeed: 1000, broadbandBaseSpeed: 0, isFTTR: true, isActive: true,
    extras: 'FTTR1+1, 权益超市铂金', monthlyTotal: 149,
    targetCarrier: 'all', planCategory: 'fttr' },
  { id: '20253105', name: '169元5GA全家享(全光版)', price: 169, data: 200, voice: 2000,
    hasBroadband: true, broadbandSpeed: 1000, broadbandBaseSpeed: 0, isFTTR: true, isActive: true,
    extras: 'FTTR1+1, 3天全天云存+AI', monthlyTotal: 169,
    targetCarrier: 'all', planCategory: 'fttr' },
  { id: '20253106', name: '199元5GA全家享(全光版)', price: 199, data: 240, voice: 3000,
    hasBroadband: true, broadbandSpeed: 2000, broadbandBaseSpeed: 0, isFTTR: true, isActive: true,
    extras: 'FTTR1+1, 3天全天云存+AI', monthlyTotal: 199,
    targetCarrier: 'all', planCategory: 'fttr' },
  { id: '20253107', name: '239元5GA全家享(全光版)', price: 239, data: 280, voice: 3200,
    hasBroadband: true, broadbandSpeed: 2000, broadbandBaseSpeed: 0, isFTTR: true, isActive: true,
    extras: 'FTTR1+1, 3天全天云存+AI', monthlyTotal: 239,
    targetCarrier: 'all', planCategory: 'fttr' },

  // --- 竞争资费 (异网用户专用) ---
  { id: '20263026', name: '45元全家享（AI爱家版）竞争资费', price: 39, data: 40, voice: 500,
    hasBroadband: true, broadbandSpeed: 1000, broadbandBaseSpeed: 500, isFTTR: false, isActive: true,
    extras: 'WIFI6路由器', monthlyTotal: 45,
    targetCarrier: 'competitor', planCategory: 'competitive' },
  { id: '20253027', name: '55元全家享爱家基础版', price: 49, data: 60, voice: 700,
    hasBroadband: true, broadbandSpeed: 1000, broadbandBaseSpeed: 500, isFTTR: false, isActive: true,
    extras: 'WIFI6路由器', monthlyTotal: 55,
    targetCarrier: 'competitor', planCategory: 'competitive' },
  { id: '999001810566563', name: '300包年融合活动', price: 25, data: 40, voice: 500,
    hasBroadband: true, broadbandSpeed: 1000, broadbandBaseSpeed: 500, isFTTR: false, isActive: true,
    extras: 'WIFI6路由器(年付300)', monthlyTotal: 25,
    targetCarrier: 'competitor', planCategory: 'competitive' },
  { id: '999001810523252', name: '60元5G全家享惠民资费（教育版）', price: 59, data: 250, voice: 1500,
    hasBroadband: true, broadbandSpeed: 1000, broadbandBaseSpeed: 500, isFTTR: false, isActive: true,
    extras: 'WIFI6路由器+爱家教育包', monthlyTotal: 60,
    targetCarrier: 'competitor', planCategory: 'competitive' },
];

// ─────────────────────────────────────────────
// 用户清单 Excel 列名 → 字段名 映射
// 与 /Volumes/Harry/S1/小工具开发/用户清单（清洗）.xlsx 表头完全对齐
// ─────────────────────────────────────────────
export const CSV_HEADER_MAP: Record<string, string> = {
  '县市': 'province',
  '网格': 'grid',
  '地址': 'address',
  '姓名': 'name',
  '联系电话': 'phone',
  '归属运营商': 'carrier',
  '客户类型': 'customerType',
  '年龄': 'age',
  '民族': 'ethnicity',
  '结余金额': 'balance',
  '套餐名称': 'currentPlanName',
  '套餐档位': 'currentPrice',
  '是否宽带客户': 'hasBroadband',
  '宽带带宽': 'broadbandSpeed',
  '近三月月均折前ARPU(元)': 'arpu3Month',
  '近三月月均折后ARPU': 'arpu3MonthAfter',
  '近三月DOU（GB）': 'avgData',
  '近三月MOU': 'avgVoice',
  '近三月月均语音+流量超套金额': 'overageAmount',
  '近三月月均家新+个新+新兴超消金': 'extraConsumption',
  '是否是0合约客户': 'isZeroContract',
  '是否是老旧套餐': 'isOldPlan',
  '是否是同证新增': 'isSameCertNew',
  '是否是异网双卡': 'isDualCard',
  '是否是我号异宽': 'isMyNumOtherBroadband',
  '是否是拍照低网龄': 'isLowNetworkAge',
  '一事一案名称': 'specialCase',
};

// 套餐管理 Excel 列名 → 字段名 映射
export const PLAN_HEADER_MAP: Record<string, string> = {
  '套餐编码': 'id',
  '套餐名称': 'name',
  '资费': 'price',
  '月费总额': 'monthlyTotal',
  '流量': 'data',
  '语音': 'voice',
  '是否含宽带': 'hasBroadband',
  '宽带速率': 'broadbandSpeed',
  '原始宽带速率': 'broadbandBaseSpeed',
  '是否FTTR': 'isFTTR',
  '其他权益': 'extras',
  '搭载产品': 'bundledProductsText',
  '办理条件': 'requiredConditions',
  '目标用户': 'targetCarrier',
  '套餐分类': 'planCategory',
  '是否上架': 'isActive',
};

// 导入用户清单时的必填/选填列说明（用于模板下载和校验提示）
export const REQUIRED_HEADERS = [
  { name: '联系电话', required: true, desc: '用户唯一标识' },
  { name: '姓名', required: false, desc: '用户姓名' },
  { name: '县市', required: false, desc: '归属县市' },
  { name: '网格', required: false, desc: '所属网格' },
  { name: '地址', required: false, desc: '用户地址' },
  { name: '归属运营商', required: false, desc: '移动/电信/联通' },
  { name: '客户类型', required: false, desc: '拍照中高端/拍照低端等' },
  { name: '年龄', required: false, desc: '用户年龄' },
  { name: '民族', required: false, desc: '民族' },
  { name: '结余金额', required: false, desc: '账户结余' },
  { name: '套餐名称', required: false, desc: '当前使用的套餐名' },
  { name: '套餐档位', required: true, desc: '当前套餐月费 (数值)' },
  { name: '是否宽带客户', required: false, desc: '1=是, 0=否' },
  { name: '宽带带宽', required: false, desc: 'Mbps (数值)' },
  { name: '近三月月均折前ARPU(元)', required: true, desc: '折前平均月消费 (数值)' },
  { name: '近三月月均折后ARPU', required: false, desc: '折后平均月消费 (数值)' },
  { name: '近三月DOU（GB）', required: true, desc: '月均流量使用量 (GB)' },
  { name: '近三月MOU', required: true, desc: '月均通话时长 (分钟)' },
  { name: '近三月月均语音+流量超套金额', required: false, desc: '超出套餐的费用' },
  { name: '近三月月均家新+个新+新兴超消金', required: false, desc: '额外消费金额' },
  { name: '是否是0合约客户', required: false, desc: '1=是, 0=否' },
  { name: '是否是老旧套餐', required: false, desc: '1=是, 0=否' },
  { name: '是否是同证新增', required: false, desc: '1=是, 0=否' },
  { name: '是否是异网双卡', required: false, desc: '1=是, 0=否' },
  { name: '是否是我号异宽', required: false, desc: '1=是, 0=否' },
  { name: '是否是拍照低网龄', required: false, desc: '1=是, 0=否' },
  { name: '一事一案名称', required: false, desc: '特殊营销方案名称' },
];

// 套餐管理导入模板列说明
export const PLAN_REQUIRED_HEADERS = [
  { name: '套餐编码', required: true, desc: '套餐唯一标识' },
  { name: '套餐名称', required: true, desc: '用于推荐和展示的套餐名称' },
  { name: '资费', required: true, desc: '主套餐月费，数值类型' },
  { name: '月费总额', required: false, desc: '含搭载业务的总月费，空则等于资费' },
  { name: '流量', required: true, desc: '套餐流量，单位 GB' },
  { name: '语音', required: true, desc: '套餐语音分钟数' },
  { name: '是否含宽带', required: true, desc: '是/否' },
  { name: '宽带速率', required: false, desc: '宽带速率 Mbps，无宽带填 0' },
  { name: '原始宽带速率', required: false, desc: '提速前速率(>0表示需千兆提速包)，无提速填0' },
  { name: '是否FTTR', required: false, desc: '是/否' },
  { name: '其他权益', required: false, desc: '会员、云存、安防等' },
  { name: '搭载产品', required: false, desc: '必搭载业务名称，多项用+分隔' },
  { name: '办理条件', required: false, desc: '如：主套餐59元及以下办理' },
  { name: '目标用户', required: false, desc: 'all=全部/competitor=仅异网' },
  { name: '套餐分类', required: false, desc: 'personal/broadband/fttr/competitive' },
  { name: '是否上架', required: false, desc: '是/否，默认是' },
];
